language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make publish
- make github
env:
  global:
  - secure: "E0hqFlcpoDa34PImCGOPXqAeuETQrGAMi3QLh9b3vmln6nwm1WhRJG0uiodp1VzeU2ahjhgPrYqVgKsVPezbxf4ZVMUyiMw/TdZKHASfueBOBFJWPIel1rf3efRmKwbxGOd04OYAgfWH6onDMgLJp5asCqCo96pd7YU/CA5dIhiGsZtpNNrsuBmFM2YWIN2xRfuJwFjL6345jD5zW16F9/qIWZoIVELlHzdOfN1tWFFCvmBOOpDFh8Di+zOdqnw7nmd1bRh7KZJsWlgGOOcYwTRHS79KSgkLrU/4DcRyAO0zgDunyj9bfWRLYtfXNQhoPSj7Ewl706262Q6kVPO4YXz8ZxC5xKXsMwBk4DAvqSHSeLnHsn/WFjmLaZkC+96nkMoxg/kllqU3ILHVJx3AqOX+1HgKvqMvfO8CA1bsFy1BmYNtAdXm5ru0ke6QIIzjW0Gc8s+HDYtVWJU0bO1UBzx5UtKeAmMPvgUUR8macDlrmIPNYm+rCcMNrp6wKIEgH4unvuwoE4VYW6qXkF48XnWqzQtwFEKsuE5lkeQWkaF6Jat2t2pvK8ymN1Wxbgc50+teaWmq2yE1Ev8rjfsnQZ9KDWrkOvPOClYsvkV8Nnkrewb3AT4ny+0FnyBK8LlzKDpVn3LRxR0UKrHVOLR6hZAdkgVHJ6WbHCBbppFXJ5Y="
